# Домашнее задание к занятию "Собственные домены ошибок"

## Правила выполнения домашней работы:

* При сдаче домашнего задания в поле для сдачи работы прикрепите ссылку на Pull Request с кодом на проверку внутри вашего проекта в Git.
* Все задачи обязательны к выполнению для получения зачета, кроме задач со звездочкой. Присылать на проверку можно каждую задачу по отдельности или все задачи вместе. Во время проверки по частям ваша домашняя работа будет со статусом "На доработке".
* Любые вопросы по решению задач задавайте в чате учебной группы.

## Задание 1
1. Найти в вашем приложении места, где есть возможность неблагоприятного исхода и требуется сообщить пользователю об этом. 
2. Создайте собственный домен ошибок (перечисление). 
3. Добавьте в него случаи, которые могут быть. 
4. Покажите пользователю Alert, уведомив его об ошибке.

## Задание 2
Примените тип `Result` для асинхронного вызова, обработайте результат через `switch`.

## Задание 3
Переделайте один из методов, который возвращает `nil` в неблагоприятном исходе, используя функцию, которая выбрасывает исключение в этом случае (`throws`).

## Задание 4*
Найдите место в вашей программе, где дальнейшее ее выполнение не имеет смысла, если определенное условие не выполнено, воспользуйтесь `preconditionFailure` и `guard`.

